[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r backend/requirements-render.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm install",
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
